# Generated by Django 4.0.1 on 2022-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=60)),
                ('Student_Marks', models.FloatField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_Number', models.IntegerField()),
                ('Highest_Qualification', models.CharField(max_length=60)),
                ('Passport_Photo', models.ImageField(upload_to='images/')),
                ('Resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
