# Generated by Django 4.0.1 on 2022-02-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Highest_Qualification',
            new_name='Book_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Mobile_Number',
            new_name='Book_Price',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Passport_Photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_Marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_Name',
        ),
        migrations.AddField(
            model_name='student',
            name='Book_code',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
